Java crash - AID_SYSTEM_USER - SimListDialogFragment.updateDialog - java.lang.NullPointerException.
This error may be because onCreateDialog did not initialize mSubscriptions correctly, causing it to be null.
java.lang.RuntimeException: java.lang.NullPointerException at com.android.settings.sim.SimListDialogFragment.updateDialog.

Fix: 194175217
Test: Manual Test
Change-Id: I761fed847441c6061ea4690658f06b9c2021bcee